---
- name: Set NTP server on MikroTik devices
  hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli

  vars:
    ansible_user: "{{ router_username }}"
    ansible_password: "{{ router_password }}"
    ansible_network_os: community.routeros.routeros
    ntp_server: "{{ ntp_server }}"
    server_dns_names: "{{ server_dns_names }}"

  tasks:
    - name: Setting NTP Server Settings
      community.routeros.command:
        commands:
          - system ntp client set primary-ntp={{ ntp_server }}
          - system ntp client set secondary-ntp={{ ntp_server }}
          - system ntp client set server-dns-names={{ server_dns_names }}
