---
- name: Set NTP server on MikroTik devices
  hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli

  vars:
    ansible_user: "{{ router_username }}"
    ansible_password: "{{ router_password }}"
    ansible_network_os: community.routeros.routeros
    ntp_server: "{{ ntp_server }}"
    server-dns-names: "{{ server-dns-names }}"
   
    

  tasks:
    - name: Set primary NTP server
      community.routeros.command:
        commands:
          - /system/ntp/client/set enabled=yes primary-ntp={{ ntp_server }}
          - /system/ntp/client/set enabled=yes secondary-ntp={{ ntp_server }}
          - /system/ntp/client/set server-dns-names={{ server-dns-names }}
